version: '3.7'

volumes:
    logs:
        driver: local

services:
    api:
        build:
            context: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            - DOCKER=1
        ports:
            - ${SERVICE_PORT}:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
        image: library/mysql:8.0.20
        ports:
        - "${MYSQL_PORT}:3306"
        environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
